
/** How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2 <= b <= 100? */
object Problem_029 extends App {
  val terms = (for (a <- 2 to 100; b <- 2 to 100) yield BigInt(a).pow(b))
  assert (9183 == terms.groupBy(x => x).size)
}