package euler.level_02

import org.junit.Assert._
import org.junit.Test

/**
 * How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2 <= b <= 100?
 */
final class Test_029 {

  @Test def verifyAnswer() {
    val ExpectedAnswer = 9183
    val terms = (for (a <- 2 to 100; b <- 2 to 100) yield BigInt(a).pow(b))
    assertEquals(ExpectedAnswer, terms.groupBy(x => x).size)

  }
}